/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainFrame.java
 *
 * Created on Mar 17, 2012, 9:22:29 PM
 */

package com.github.xtutran.ui;

import com.github.xtutran.DesktopMonitoring;
import com.github.xtutran.TaskFactory;
import com.github.xtutran.detection.Message;
import com.github.xtutran.ftp.FTPClientHelper;
import com.github.xtutran.ui.service.utilizer.Config;
import org.apache.commons.io.FileUtils;

import javax.swing.*;
import java.awt.*;
import java.io.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.LinkedList;
import java.util.Timer;

;

/**
 * @author kekkaishi
 */
public class MainFrame extends javax.swing.JFrame {

    public static MainFrame currentFrame;
    public static File fileReport = new File("report.txt");
    // Variables declaration - do not modify
    private javax.swing.JLabel CurrentTime;
    private javax.swing.JLabel TotalBilledTime;
    private javax.swing.JLabel currentIdleTime;
    private javax.swing.JLabel currentTime;
    private javax.swing.JLabel detectMomentResult;
    private javax.swing.JLabel idleThreshold;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton pauseButton;
    private javax.swing.JButton settingButton;
    private javax.swing.JButton startButton;
    private javax.swing.JLabel startTime;
    private javax.swing.JButton stopButton;
    private javax.swing.JLabel timerPauseTime;
    private javax.swing.JLabel totalIdleTime;
    private javax.swing.JTextArea tracerlogTextField;
    private javax.swing.JButton viewreportButton;
    private java.awt.Container main;
    private java.awt.Container login;
    private java.awt.Container settings;
    private java.awt.Container togglePanel;
    private SettingForm settingPanel;
    private Timer updateDateTime;
    private Timer updateLogTime;
    private TrayIcon trayIcon;
    private SystemTray sysTray;
    // End of variables declaration
    // detectMomentResult.setVisible(false);
    // currentIdleTime.setVisible(false);
    // timerPauseTime.setVisible(false);
    private String detectMomentResultString = "NO MOVEMENT DETECTED";
    private String currentIdleTimeString = "";
    private String timerPauseTimeString = "Timer will Pause in "
            + TaskFactory.timeToPause + " Seconds";
    private String beginTime = "";
    private String endTime = "";
    private int workingTime;
    private int idleTime;

    private FTPClientHelper ftp;

    /**
     * Creates new form MainFrame
     */
    private MainFrame() {

        initComponents();
        // setDefaultCloseOperation(HIDE_ON_CLOSE);
        main = this.getRootPane().getContentPane();
        settingPanel = new SettingForm(this);
        settings = settingPanel;
        login = new LoginSettingsPanel(this);
        togglePanel = settingPanel;
        currentFrame = this;
        turnOffWarningMessage();

        setDefaultCloseOperation(javax.swing.JFrame.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }

            public void windowIconified(java.awt.event.WindowEvent evt) {
                formWindowIconified(evt);
            }
        });

        this.setResizable(false);
        this.totalIdleTime.setSize(this.TotalBilledTime.getWidth() + 10,
                this.totalIdleTime.getSize().height);
    }

    public static MainFrame getInstance() {
        if (currentFrame == null) {
            currentFrame = new MainFrame();
        }
        return currentFrame;
    }

    public void setFTP(FTPClientHelper ftp) {
        this.ftp = ftp;
    }

    public FTPClientHelper getFtp() {
        return this.ftp;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        CurrentTime = new javax.swing.JLabel();
        TotalBilledTime = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tracerlogTextField = new javax.swing.JTextArea();
        viewreportButton = new javax.swing.JButton();
        settingButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        currentTime = new javax.swing.JLabel();
        startTime = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        idleThreshold = new javax.swing.JLabel();
        totalIdleTime = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        detectMomentResult = new javax.swing.JLabel();
        currentIdleTime = new javax.swing.JLabel();
        timerPauseTime = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        startButton = new javax.swing.JButton();
        pauseButton = new javax.swing.JButton();
        stopButton = new javax.swing.JButton();
        startButton.setEnabled(true);
        pauseButton.setEnabled(false);
        stopButton.setEnabled(false);

        jPanel4.setName("jPanel4"); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(
                jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(jPanel4Layout.createParallelGroup(
                javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 100,
                Short.MAX_VALUE));
        jPanel4Layout.setVerticalGroup(jPanel4Layout.createParallelGroup(
                javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 100,
                Short.MAX_VALUE));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N

        CurrentTime.setBackground(new Color(240, 240, 240)); // NOI18N
        CurrentTime.setFont(new Font("Tahoma", Font.BOLD, 17)); // NOI18N
        CurrentTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CurrentTime.setText("February 10 2012, 1:30 pm"); // NOI18N
        CurrentTime
                .setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        CurrentTime.setName("CurrentTime"); // NOI18N

        TotalBilledTime.setBackground(new Color(0, 51, 255)); // NOI18N
        TotalBilledTime.setFont(new java.awt.Font("Tahoma", 1, 15));
        TotalBilledTime.setForeground(new Color(255, 255, 255)); // NOI18N
        TotalBilledTime
                .setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TotalBilledTime.setText("TOTAL Billed Time Today:"); // NOI18N
        TotalBilledTime
                .setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        TotalBilledTime.setName("TotalBilledTime"); // NOI18N
        TotalBilledTime.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
                jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(
                javax.swing.GroupLayout.Alignment.LEADING).addComponent(
                TotalBilledTime, javax.swing.GroupLayout.DEFAULT_SIZE, 501,
                Short.MAX_VALUE).addComponent(CurrentTime,
                javax.swing.GroupLayout.Alignment.TRAILING,
                javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE));
        jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(
                javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                javax.swing.GroupLayout.Alignment.TRAILING,
                jPanel1Layout.createSequentialGroup().addComponent(CurrentTime,
                        javax.swing.GroupLayout.DEFAULT_SIZE, 28,
                        Short.MAX_VALUE).addPreferredGap(
                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TotalBilledTime,
                                javax.swing.GroupLayout.PREFERRED_SIZE, 44,
                                javax.swing.GroupLayout.PREFERRED_SIZE)));

        TotalBilledTime.setBackground(Color.BLUE);

        jPanel2.setName("jPanel2"); // NOI18N

        jLabel10.setFont(new Font("Tahoma", Font.BOLD, 15)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel10.setText("Tracker Log"); // NOI18N
        jLabel10.setName("jLabel10"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tracerlogTextField.setColumns(20);
        tracerlogTextField.setRows(5);
        tracerlogTextField.setName("tracerlogTextField"); // NOI18N
        jScrollPane1.setViewportView(tracerlogTextField);

        viewreportButton.setEnabled(false);
        viewreportButton.setFont(new Font("Tahoma", Font.BOLD, 11)); // NOI18N
        viewreportButton.setText("View Report"); // NOI18N
        viewreportButton.setName("viewreportButton"); // NOI18N
        viewreportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewreportButtonActionPerformed(evt);
            }
        });

        settingButton.setFont(new Font("Tahoma", Font.BOLD, 11)); // NOI18N
        settingButton.setText("Settings"); // NOI18N
        settingButton.setName("settingButton"); // NOI18N
        settingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
                jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout
                .setHorizontalGroup(jPanel2Layout
                        .createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(
                                jPanel2Layout
                                        .createSequentialGroup()
                                        .addComponent(
                                                jLabel10,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                100,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(401, Short.MAX_VALUE))
                        .addComponent(jScrollPane1,
                                javax.swing.GroupLayout.DEFAULT_SIZE, 501,
                                Short.MAX_VALUE)
                        .addGroup(
                                jPanel2Layout
                                        .createSequentialGroup()
                                        .addGap(136, 136, 136)
                                        .addComponent(
                                                viewreportButton,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                113,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(
                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(
                                                settingButton,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                108,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(138, Short.MAX_VALUE)));
        jPanel2Layout
                .setVerticalGroup(jPanel2Layout
                        .createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(
                                jPanel2Layout
                                        .createSequentialGroup()
                                        .addComponent(
                                                jLabel10,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                24,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(
                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(
                                                jScrollPane1,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                215,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(
                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(
                                                jPanel2Layout
                                                        .createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                false)
                                                        .addComponent(
                                                                settingButton,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                Short.MAX_VALUE)
                                                        .addComponent(
                                                                viewreportButton,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                42,
                                                                Short.MAX_VALUE))));

        jPanel3.setName("jPanel3"); // NOI18N

        currentTime.setFont(new Font("Tahoma", Font.PLAIN, 100)); // NOI18N
        currentTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        currentTime.setText("00:00"); // NOI18N
        currentTime
                .setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        currentTime.setName("currentTime"); // NOI18N
        currentTime.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        startTime.setFont(new Font("Tahoma", Font.BOLD, 15)); // NOI18N
        startTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        startTime
                .setText("Start time:                                    End Time:"); // NOI18N
        startTime.setName("startTime"); // NOI18N

        jPanel6.setName("jPanel6"); // NOI18N

        jLabel5.setText("Total Idle Time: "); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        jPanel5.setName("jPanel5"); // NOI18N

        jLabel4.setText("Idle Threshold:"); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        idleThreshold.setFont(new Font("Tahoma", Font.BOLD, 11)); // NOI18N
        idleThreshold.setText(TaskFactory.timeToPause + " seconds"); // NOI18N
        idleThreshold.setName("idleThreshold"); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(
                jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout
                .setHorizontalGroup(jPanel5Layout
                        .createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(
                                jPanel5Layout
                                        .createSequentialGroup()
                                        .addComponent(
                                                jLabel4,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                89,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(
                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(
                                                idleThreshold,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                63,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)));
        jPanel5Layout.setVerticalGroup(jPanel5Layout.createParallelGroup(
                javax.swing.GroupLayout.Alignment.LEADING).addComponent(
                idleThreshold, javax.swing.GroupLayout.DEFAULT_SIZE,
                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

        totalIdleTime.setFont(new Font("Tahoma", Font.BOLD, 11)); // NOI18N

        totalIdleTime.setText(""); // NOI18N
        totalIdleTime.setName("totalIdleTime"); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(
                jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout
                .setHorizontalGroup(jPanel6Layout
                        .createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(
                                jPanel6Layout
                                        .createSequentialGroup()
                                        .addContainerGap(30, Short.MAX_VALUE)
                                        .addComponent(
                                                jLabel5,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                99,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(
                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(
                                                totalIdleTime,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                69,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(
                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                50, Short.MAX_VALUE)
                                        .addComponent(
                                                jPanel5,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)));
        jPanel6Layout
                .setVerticalGroup(jPanel6Layout
                        .createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(
                                javax.swing.GroupLayout.Alignment.TRAILING,
                                jPanel6Layout
                                        .createSequentialGroup()
                                        .addGroup(
                                                jPanel6Layout
                                                        .createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(
                                                                jPanel5,
                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                Short.MAX_VALUE)
                                                        .addComponent(
                                                                totalIdleTime,
                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                Short.MAX_VALUE)
                                                        .addComponent(
                                                                jLabel5,
                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                Short.MAX_VALUE))
                                        .addContainerGap()));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(
                jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(
                javax.swing.GroupLayout.Alignment.LEADING).addComponent(
                currentTime, javax.swing.GroupLayout.DEFAULT_SIZE, 501,
                Short.MAX_VALUE).addComponent(startTime,
                javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
                .addGroup(
                        jPanel3Layout.createSequentialGroup()
                                .addGap(32, 32, 32).addComponent(jPanel6,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(59, Short.MAX_VALUE)));
        jPanel3Layout
                .setVerticalGroup(jPanel3Layout
                        .createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(
                                jPanel3Layout
                                        .createSequentialGroup()
                                        .addComponent(
                                                currentTime,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                88,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(
                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(
                                                startTime,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                27,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(
                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(
                                                jPanel6,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE)
                                        .addContainerGap()));

        jPanel7.setBackground(new Color(204, 0, 0)); // NOI18N
        jPanel7.setName("jPanel7"); // NOI18N

        detectMomentResult.setFont(new Font("Tahoma", Font.BOLD, 19)); // NOI18N
        detectMomentResult.setForeground(new Color(255, 255, 255)); // NOI18N
        detectMomentResult
                .setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        detectMomentResult.setText("NO MOVEMENT DETECTED"); // NOI18N
        detectMomentResult.setName("detectMomentResult"); // NOI18N

        currentIdleTime.setForeground(new Color(255, 255, 255)); // NOI18N
        currentIdleTime
                .setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        currentIdleTime.setText("Idle 45 seconds"); // NOI18N
        currentIdleTime.setName("currentIdleTime"); // NOI18N

        timerPauseTime.setForeground(new Color(255, 255, 255)); // NOI18N
        timerPauseTime.setText("Timer will Pause in " + TaskFactory.timeToPause
                + " Seconds"); // NOI18N
        timerPauseTime.setName("timerPauseTime"); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(
                jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout
                .setHorizontalGroup(jPanel7Layout
                        .createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(detectMomentResult,
                                javax.swing.GroupLayout.DEFAULT_SIZE, 501,
                                Short.MAX_VALUE)
                        .addGroup(
                                jPanel7Layout
                                        .createSequentialGroup()
                                        .addComponent(
                                                currentIdleTime,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                168,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(
                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                89, Short.MAX_VALUE)
                                        .addComponent(
                                                timerPauseTime,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                244,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)));
        jPanel7Layout
                .setVerticalGroup(jPanel7Layout
                        .createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(
                                jPanel7Layout
                                        .createSequentialGroup()
                                        .addComponent(
                                                detectMomentResult,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                41,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(
                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(
                                                jPanel7Layout
                                                        .createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(
                                                                timerPauseTime,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                25,
                                                                Short.MAX_VALUE)
                                                        .addComponent(
                                                                currentIdleTime,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                25,
                                                                Short.MAX_VALUE))));

        jPanel8.setName("jPanel8"); // NOI18N

        startButton.setText("Start"); // NOI18N
        startButton.setName("startButton"); // NOI18N
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        pauseButton.setText("Pause"); // NOI18N
        pauseButton.setName("pauseButton"); // NOI18N
        pauseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(
                jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(jPanel8Layout.createParallelGroup(
                javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                jPanel8Layout.createSequentialGroup().addContainerGap()
                        .addComponent(startButton,
                                javax.swing.GroupLayout.PREFERRED_SIZE, 128,
                                javax.swing.GroupLayout.PREFERRED_SIZE).addGap(
                        55, 55, 55).addComponent(pauseButton,
                        javax.swing.GroupLayout.PREFERRED_SIZE, 128,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(36, Short.MAX_VALUE)));
        jPanel8Layout.setVerticalGroup(jPanel8Layout.createParallelGroup(
                javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                jPanel8Layout.createParallelGroup(
                        javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pauseButton,
                                javax.swing.GroupLayout.PREFERRED_SIZE, 71,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(startButton,
                                javax.swing.GroupLayout.PREFERRED_SIZE, 71,
                                javax.swing.GroupLayout.PREFERRED_SIZE)));

        stopButton.setText("Stop"); // NOI18N
        stopButton.setName("stopButton"); // NOI18N
        stopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
                getContentPane());
        getContentPane().setLayout(layout);
        layout
                .setHorizontalGroup(layout
                        .createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE)
                        .addComponent(jPanel3,
                                javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE)
                        .addComponent(jPanel7,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE)
                        .addGroup(
                                layout
                                        .createSequentialGroup()
                                        .addComponent(
                                                jPanel8,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE)
                                        .addPreferredGap(
                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(
                                                stopButton,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                128,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap()).addComponent(
                                jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE));
        layout
                .setVerticalGroup(layout
                        .createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(
                                layout
                                        .createSequentialGroup()
                                        .addComponent(
                                                jPanel1,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(
                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(
                                                jPanel3,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                150,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(
                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(
                                                jPanel7,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(
                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(
                                                layout
                                                        .createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(
                                                                jPanel8,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(
                                                                stopButton,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                71,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(
                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(
                                                jPanel2,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap()));

        Image iconImage = Toolkit.getDefaultToolkit().getImage("icon.jpg");
        trayIcon = new TrayIcon(iconImage, "Java monitoring");
        trayIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                trayIconMouseClicked(evt);
            }
        });

        pack();
    }// </editor-fold>

    private void formWindowClosing(java.awt.event.WindowEvent evt) {
        // TODO add your handling code here:
        // this.hideWindow();
        int n = JOptionPane.showConfirmDialog(this,
                "Do you want to exit monitoring program?", "Exit program",
                JOptionPane.YES_NO_OPTION);
        if (n == 0) {
            this.dispose();
            System.exit(1);
        }
    }

    private void formWindowIconified(java.awt.event.WindowEvent evt) {
        // TODO add your handling code here:
        this.hideWindow();
    }

    private void restoreWindow() {
        SystemTray.getSystemTray().remove(trayIcon);
        this.setState(javax.swing.JFrame.NORMAL);
        this.setExtendedState(javax.swing.JFrame.NORMAL);
        this.setAlwaysOnTop(true);
        this.toFront();
        this.requestFocusInWindow();
        // this.setFocusable(true);
        // this.setFocusableWindowState(true);
        // this.setAlwaysOnTop(false);
        this.setVisible(true);
    }

    private void hideWindow() {
        this.setVisible(false);
        try {
            SystemTray.getSystemTray().add(trayIcon);
        } catch (AWTException e) {
            System.out.println("System Tray unsupported!");
        }
    }

    private void trayIconMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        if (evt.getButton() == java.awt.event.MouseEvent.BUTTON1)
            restoreWindow();

    }

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        System.out.println("Start");
        startButton.setEnabled(false);
        pauseButton.setEnabled(true);
        stopButton.setEnabled(true);

        DateFormat dateFormat = new SimpleDateFormat("hh:mm a");
        // get current date time with Calendar()
        Calendar currentTime = Calendar.getInstance();
        beginTime = "Start time : " + dateFormat.format(currentTime.getTime());
        endTime = "End time :              ";

        startTime.setText(beginTime + "                 " + endTime);
        DesktopMonitoring.setStatus(DesktopMonitoring.RUNNING);
        TaskFactory.restartLogTasks();
    }

    private void pauseButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        System.out.println("Pause");
        startButton.setEnabled(true);
        pauseButton.setEnabled(false);
        stopButton.setEnabled(true);
        DesktopMonitoring.setStatus(DesktopMonitoring.PAUSED);
        TaskFactory.cancelLogTasks();
    }

    private void stopButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        System.out.println("Stop");

        Object[] options = {"OK", "CANCEL"};
        int selected = JOptionPane.showOptionDialog(this,
                "Do you really want to stop working?", "Warning",
                JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null,
                options, options[0]);
        if (selected == 0) {
            startButton.setEnabled(false);
            pauseButton.setEnabled(false);
            stopButton.setEnabled(false);
            DateFormat dateFormat = new SimpleDateFormat("hh:mm a");
            // get current date time with Calendar()
            Calendar currentTime = Calendar.getInstance();
            endTime = "End time : " + dateFormat.format(currentTime.getTime());
            startTime.setText(beginTime + "             " + endTime);
            DesktopMonitoring.setStatus(DesktopMonitoring.STOPPED);
            TaskFactory.cancelLogTasks();
            viewreportButton.setEnabled(true);
            saveReport();
        }
    }

    private void viewreportButtonActionPerformed(java.awt.event.ActionEvent evt) {
        viewReport();
        System.out.println("View Report");
    }

    private void settingButtonActionPerformed(java.awt.event.ActionEvent evt) {
        System.out.println("Settings");
        this.setContentPane(login);
    }

    public void backToMainPanel() {
        this.setContentPane(main);
    }

    public void turnToSettingPanel() {
        this.setContentPane(settings);
    }

    public void setContentPane(Container pane) {
        this.getRootPane().setContentPane(pane);
        // togglePanel = mainPanel;
        // mainPanel = this.getRootPane().getContentPane();
        pack();
    }

    public void updateLog() {
        tracerlogTextField.setText(Message.getLogRepresentation());
        tracerlogTextField.setCaretPosition(tracerlogTextField
                .getCaretPosition()
                + tracerlogTextField.getText().length());
        tracerlogTextField.repaint();
    }

    public void setTextTime(String time) {
        CurrentTime.setText(time);
    }

    public void setTimeCounter(int aggregateTime) {
        this.workingTime = aggregateTime;
        int minute = aggregateTime / 60;
        int hour = minute / 60;
        currentTime.setText(hour + " : " + minute % 60);
        TotalBilledTime.setText("TOTAL Billed Time Today: " + minute
                + " minutes");
        currentTime.repaint();
    }

    public void setTotalIdleTime(int _totalIdleTime) {
        this.idleTime = _totalIdleTime;
        totalIdleTime.setText(_totalIdleTime / 60 + " minutes");
        totalIdleTime.repaint();
    }

    public void setCurrentIdleTime(int _currentIdleTime) {
        currentIdleTimeString = "Idle: " + _currentIdleTime + " seconds";
        currentIdleTime.setText(currentIdleTimeString);
        currentIdleTime.repaint();
        if (_currentIdleTime >= TaskFactory.timeToPause) {
            temporaryPause();
        }
        if (_currentIdleTime > TaskFactory.updateTime) {
            turnOnWarningMessage();
        } else {
            turnOffWarningMessage();
        }
    }

    public void temporaryPause() {
        jPanel7.setBackground(new Color(204, 0, 0));
        jPanel7.setForeground(new Color(255, 255, 255));
        detectMomentResult.setText("Temporary pause");
        System.out.println("Temporary pause");
        currentIdleTime.setText("");
        timerPauseTime.setText("");
    }

    private void turnOnWarningMessage() {
        jPanel7.setBackground(new Color(204, 0, 0));
        jPanel7.setForeground(new Color(255, 255, 255));
        detectMomentResult.setText(detectMomentResultString);
        System.out.println(detectMomentResultString
                + "detectMomentResultString");
        currentIdleTime.setText(currentIdleTimeString);
        timerPauseTime.setText(timerPauseTimeString);
    }

    private void turnOffWarningMessage() {
        jPanel7.setBackground(new Color(240, 240, 240));
        detectMomentResult.setText("");
        currentIdleTime.setText("");
        timerPauseTime.setText("");
    }

    private String prepareReport() {
        StringBuilder sb = new StringBuilder();

        DateFormat dateFormat = new SimpleDateFormat("MM-dd-yyyy");
        DateFormat dateFormat2 = new SimpleDateFormat("hh:mm a");

        // get current date time with Calendar()
        Calendar currentTime = Calendar.getInstance();
        sb.append(dateFormat.format(currentTime.getTime()));
        sb.append(" ");
        sb.append(beginTime);
        sb.append(" ");
        sb.append("End time : " + dateFormat2.format(currentTime.getTime()));
        sb.append("|");
        sb.append(" working time ");
        sb.append(Math.round((double) workingTime / (double) 60));
        sb.append(" minutes (");
        sb.append(Math.round((double) workingTime / (double) 3600));
        sb.append(" hours )");
        sb.append("|");
        sb.append(" idle ");
        sb.append(Math.round((double) idleTime / (double) 60));
        sb.append(" minutes (");
        sb.append(Math.round((double) idleTime / (double) 3600));
        sb.append(" hours )");
        return sb.toString();
    }

//    public String getFtpUser() {
//        return this.settingPanel.FtpUsernameTextField.getText();
//    }

//    public void setFtpUser(String user) {
//        this.settingPanel.FtpUsernameTextField.setText(user);
//    }

//    public String getFtpPassword() {
//        return this.settingPanel.FtpPassTextField.getText();
//    }

//    public void setFtpPassword(String pass) {
//        this.settingPanel.FtpPassTextField.setText(pass);
//    }

    public String getFtpHost() {
        return Config.getInstance().getHost();
    }

//    public void setFtpHost(String host) {
//        this.settingPanel.FtpServerTextField.setText(host);
//    }

    public String getFtpFolder() {
        return Config.getInstance().getFTPFolder();
    }

    public void saveReport() {
        BufferedWriter bw;
        try {
            DateFormat folderFormat = new SimpleDateFormat("MM-dd-yyyy");

            Calendar cal = Calendar.getInstance();
            String ftpFolder = getFtpFolder() + "/" + folderFormat.format(cal.getTime());

            String nextReport = prepareReport();
            System.out.println(nextReport);

            StringBuilder lastDate = new StringBuilder();
            StringBuilder lastBeginTime = new StringBuilder();
            LinkedList<String> reports = getReport(lastDate, lastBeginTime);

            if (!nextReport.substring(0, 10).equals(lastDate.toString())) {
                System.out.println("hoho");
                reports = new LinkedList<String>();
            }

            bw = new BufferedWriter(new FileWriter(fileReport, false));

            System.out.println(lastDate.toString() + "asdfadsfasdf" + lastBeginTime.toString());
            if (nextReport.substring(24, 29).equals(lastBeginTime.toString())) {
                System.out.println("haha");
                if (reports.size() != 0) {
                    reports.removeLast();
                }
                reports.add(nextReport);
            } else {
                reports.add(nextReport);
            }

            for (String report : reports) {
                bw.write(report);
                bw.newLine();
            }

            // bw.newLine() ;
            bw.close();

            if (ftp != null) {
                ftp.uploadFile(fileReport.getAbsolutePath(), ftpFolder + "/" + fileReport.getName());
            }
            FileUtils.deleteQuietly(fileReport);

        } catch (IOException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void viewReport() {
        ReportPanel rp = new ReportPanel();
        String content = "";
        StringBuilder lastDate = new StringBuilder();
        StringBuilder lastBeginTime = new StringBuilder();
        LinkedList<String> reports = getReport(lastDate, lastBeginTime);
        for (int i = 0; i < reports.size(); i++) {
            content += reports.get(i);
            content += "\n";
        }
        rp.setVisible(true);
        rp.setText(content);
    }

    private LinkedList<String> getReport(StringBuilder lastDate, StringBuilder lastBeginTime) {
        LinkedList<String> reports = new LinkedList<String>();
        BufferedReader br;
        try {
            br = new BufferedReader(new FileReader(fileReport));

            String line;
            String date = "";
            String beginTime = "";
            while ((line = br.readLine()) != null) {
                // Print the content on the console
                date = line.substring(0, 10);
                beginTime = line.substring(24, 29);
                // System.out.println("lastDate " + lastDate);
                // System.out.println("lastBeginTime " + lastBeginTime);
                reports.add(line);
            }
            lastDate.append(date);
            lastBeginTime.append(beginTime);

        } catch (FileNotFoundException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        } catch (IOException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
        return reports;
    }
}