/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * settingForm.java
 *
 * Created on Mar 17, 2012, 11:15:09 PM
 */

package com.github.xtutran.ui;

import com.github.xtutran.TaskFactory;
import com.github.xtutran.ftp.FTPClientHelper;
import com.github.xtutran.ui.service.utilizer.Config;

import java.awt.*;

/**
 * @author kekkaishi
 */
public class SettingForm extends javax.swing.JPanel {

    // Variables declaration - do not modify
    javax.swing.JTextField FtpFolderTextField;
    javax.swing.JTextField FtpPassTextField;
    javax.swing.JTextField FtpServerTextField;
    javax.swing.JTextField FtpUsernameTextField;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField idleThresholdTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField noOfScreenShotTextField;
    private javax.swing.JButton saveButton;
    private MainFrame parent;
    /**
     * Creates new form settingForm
     */
    public SettingForm(MainFrame _parent) {
        initComponents();
        parent = _parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        idleThresholdTextField = new javax.swing.JTextField();
        noOfScreenShotTextField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        FtpServerTextField = new javax.swing.JTextField();
        FtpUsernameTextField = new javax.swing.JTextField();
        FtpPassTextField = new javax.swing.JTextField();
        FtpFolderTextField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setName("Form"); // NOI18N
        setPreferredSize(new java.awt.Dimension(501, 699));

        jLabel1.setFont(new Font("Tahoma", Font.BOLD, 15)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Settings"); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Idle Threshold Before Pausing Timer (seconds):"); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText("How many screen shots per ACTIVE minute:"); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        idleThresholdTextField.setText(TaskFactory.timeToPause + ""); // NOI18N
        idleThresholdTextField.setMaximumSize(new java.awt.Dimension(59, 20));
        idleThresholdTextField.setMinimumSize(new java.awt.Dimension(59, 20));
        idleThresholdTextField.setName("idleThresholdTextField"); // NOI18N

        noOfScreenShotTextField.setText(60 / TaskFactory.takeSnapShotTime + ""); // NOI18N
        noOfScreenShotTextField.setMaximumSize(new java.awt.Dimension(59, 20));
        noOfScreenShotTextField.setMinimumSize(new java.awt.Dimension(59, 20));
        noOfScreenShotTextField.setName("noOfScreenShotTextField"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
                jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout
                .setHorizontalGroup(jPanel1Layout
                        .createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(
                                jPanel1Layout
                                        .createSequentialGroup()
                                        .addGroup(
                                                jPanel1Layout
                                                        .createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addGroup(
                                                                jPanel1Layout
                                                                        .createSequentialGroup()
                                                                        .addGap(
                                                                                38,
                                                                                38,
                                                                                38)
                                                                        .addComponent(
                                                                                jLabel3,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                220,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGap(
                                                                                18,
                                                                                18,
                                                                                18)
                                                                        .addComponent(
                                                                                noOfScreenShotTextField,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE))
                                                        .addGroup(
                                                                jPanel1Layout
                                                                        .createSequentialGroup()
                                                                        .addGap(
                                                                                19,
                                                                                19,
                                                                                19)
                                                                        .addComponent(
                                                                                jLabel2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                252,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(
                                                                                idleThresholdTextField,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)))
                                        .addContainerGap(47, Short.MAX_VALUE)));
        jPanel1Layout
                .setVerticalGroup(jPanel1Layout
                        .createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(
                                jPanel1Layout
                                        .createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(
                                                jPanel1Layout
                                                        .createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(
                                                                jLabel2,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                24,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(
                                                                idleThresholdTextField,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(
                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(
                                                jPanel1Layout
                                                        .createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(
                                                                jLabel3,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                21,
                                                                Short.MAX_VALUE)
                                                        .addComponent(
                                                                noOfScreenShotTextField,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addContainerGap()));

        jPanel2.setName("jPanel2"); // NOI18N

        jLabel4.setFont(new Font("Tahoma", Font.BOLD, 13)); // NOI18N
        jLabel4.setText("FTP SERVER SETTINGS"); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel5.setText("FTP SERVER ADDRESSES:"); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel6.setText("FTP USERNAME"); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        jLabel7.setText("FTP PASSWORD"); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        jLabel8.setText("FTP FOLDER"); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N

        FtpServerTextField.setText(Config.getInstance().getHost()); // NOI18N
        FtpServerTextField.setName("FtpServerTextField"); // NOI18N

//        FtpUsernameTextField.setText(FTPClientHelper.username); // NOI18N
        FtpUsernameTextField.setName("FtpUsernameTextField"); // NOI18N

//        FtpPassTextField.setText(FTPClientHelper.password); // NOI18N
        FtpPassTextField.setName("FtpPassTextField"); // NOI18N

        FtpFolderTextField.setText(Config.getInstance().getFTPFolder()); // NOI18N
        FtpFolderTextField.setName("FtpFolderTextField"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
                jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout
                .setHorizontalGroup(jPanel2Layout
                        .createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(
                                jPanel2Layout
                                        .createSequentialGroup()
                                        .addGroup(
                                                jPanel2Layout
                                                        .createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(
                                                                jPanel2Layout
                                                                        .createSequentialGroup()
                                                                        .addGroup(
                                                                                jPanel2Layout
                                                                                        .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(
                                                                                                jLabel5,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                129,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addComponent(
                                                                                                jLabel6,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                100,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addComponent(
                                                                                                jLabel7)
                                                                                        .addComponent(
                                                                                                jLabel8))
                                                                        .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addGroup(
                                                                                jPanel2Layout
                                                                                        .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                false)
                                                                                        .addComponent(
                                                                                                FtpFolderTextField)
                                                                                        .addComponent(
                                                                                                FtpPassTextField)
                                                                                        .addComponent(
                                                                                                FtpUsernameTextField)
                                                                                        .addComponent(
                                                                                                FtpServerTextField,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                228,
                                                                                                Short.MAX_VALUE)))
                                                        .addGroup(
                                                                jPanel2Layout
                                                                        .createSequentialGroup()
                                                                        .addGap(
                                                                                116,
                                                                                116,
                                                                                116)
                                                                        .addComponent(
                                                                                jLabel4)))
                                        .addContainerGap(
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE)));
        jPanel2Layout
                .setVerticalGroup(jPanel2Layout
                        .createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(
                                jPanel2Layout
                                        .createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(
                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(
                                                jPanel2Layout
                                                        .createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(
                                                                jLabel5,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                19,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(
                                                                FtpServerTextField,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(
                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(
                                                jPanel2Layout
                                                        .createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel6)
                                                        .addComponent(
                                                                FtpUsernameTextField,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(
                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(
                                                jPanel2Layout
                                                        .createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel7)
                                                        .addComponent(
                                                                FtpPassTextField,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(
                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(
                                                jPanel2Layout
                                                        .createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel8)
                                                        .addComponent(
                                                                FtpFolderTextField,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addContainerGap(72, Short.MAX_VALUE)));

        jPanel3.setName("jPanel3"); // NOI18N

        saveButton.setText("Save & Exit"); // NOI18N
        saveButton.setName("saveButton"); // NOI18N
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel"); // NOI18N
        cancelButton.setName("cancelButton"); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(
                jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout
                .setHorizontalGroup(jPanel3Layout
                        .createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(
                                jPanel3Layout
                                        .createSequentialGroup()
                                        .addGap(103, 103, 103)
                                        .addComponent(saveButton)
                                        .addPreferredGap(
                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cancelButton)
                                        .addContainerGap(110, Short.MAX_VALUE)));
        jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(
                javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                javax.swing.GroupLayout.Alignment.TRAILING,
                jPanel3Layout.createSequentialGroup().addContainerGap(25,
                        Short.MAX_VALUE).addGroup(
                        jPanel3Layout.createParallelGroup(
                                javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(saveButton).addComponent(
                                cancelButton)).addContainerGap()));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(
                javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                layout.createSequentialGroup().addComponent(jLabel1,
                        javax.swing.GroupLayout.PREFERRED_SIZE, 74,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(427, Short.MAX_VALUE)).addGroup(
                javax.swing.GroupLayout.Alignment.TRAILING,
                layout.createSequentialGroup().addContainerGap(28,
                        Short.MAX_VALUE).addComponent(jPanel1,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.PREFERRED_SIZE).addGap(91, 91,
                        91)).addGroup(
                javax.swing.GroupLayout.Alignment.TRAILING,
                layout.createSequentialGroup().addContainerGap(57,
                        Short.MAX_VALUE).addGroup(
                        layout.createParallelGroup(
                                javax.swing.GroupLayout.Alignment.TRAILING,
                                false).addComponent(jPanel3,
                                javax.swing.GroupLayout.Alignment.LEADING,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE).addComponent(jPanel2,
                                javax.swing.GroupLayout.Alignment.LEADING,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE)).addGap(73, 73, 73)));
        layout
                .setVerticalGroup(layout
                        .createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(
                                layout
                                        .createSequentialGroup()
                                        .addComponent(
                                                jLabel1,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                33,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(
                                                jPanel1,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(
                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(
                                                jPanel2,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(
                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                313, Short.MAX_VALUE)
                                        .addComponent(
                                                jPanel3,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)));
    }// </editor-fold>

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {
        System.out.println("Save & Exit");
        TaskFactory.takeSnapShotTime = 60 / Integer.parseInt(noOfScreenShotTextField.getText());
        TaskFactory.timeToPause = Integer.parseInt(idleThresholdTextField.getText());
//        FTPClientHelper.host = FtpServerTextField.getText(); // NOI18N
//        FTPClientHelper.username = FtpUsernameTextField.getText(); // NOI18N
//        FTPClientHelper.password = FtpPassTextField.getText(); // NOI18N
//        FTPClientHelper.hostFolder = FtpFolderTextField.getText(); // NOI18N
        parent.backToMainPanel();
    }

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {
        System.out.println("Cancel");
        parent.backToMainPanel();
    }
    // End of variables declaration

}
